// File generated by configure_firebase_auto.py script
// DO NOT EDIT. Make changes to the script and regenerate.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtfNDX4fpARW7aEX41gtBdLmfSRmdiFss',
    appId: '1:432030718552:web:94bc32db14319583f6082d',
    messagingSenderId: '432030718552',
    projectId: 'travellooply',
    authDomain: 'travellooply.firebaseapp.com',
    storageBucket: 'travellooply.firebasestorage.app',
    measurementId: 'G-7W8Q252LZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2oSAEQEEtA67YcZ9qoRIxTkn7qPZCpTQ',
    appId: '1:432030718552:android:ce7b415e3379a2fcf6082d',
    messagingSenderId: '432030718552',
    projectId: 'travellooply',
    storageBucket: 'travellooply.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2oSAEQEEtA67YcZ9qoRIxTkn7qPZCpTQ',
    appId: '1:432030718552:android:ce7b415e3379a2fcf6082d',
    messagingSenderId: '432030718552',
    projectId: 'travellooply',
    storageBucket: 'travellooply.firebasestorage.app',
    iosBundleId: 'com.travellooply.app',
  );
}
