#!/usr/bin/env python3
"""
Automated Firebase Configuration Script for Travellooply
Generates firebase_options.dart from google-services.json and web config
"""

import json
import os

# Web Firebase Configuration (provided by user)
WEB_CONFIG = {
    "apiKey": "AIzaSyCtfNDX4fpARW7aEX41gtBdLmfSRmdiFss",
    "authDomain": "travellooply.firebaseapp.com",
    "projectId": "travellooply",
    "storageBucket": "travellooply.firebasestorage.app",
    "messagingSenderId": "432030718552",
    "appId": "1:432030718552:web:94bc32db14319583f6082d",
    "measurementId": "G-7W8Q252LZZ"
}

def extract_android_config(google_services_path):
    """Extract Android configuration from google-services.json"""
    try:
        with open(google_services_path, 'r') as f:
            data = json.load(f)
        
        project_info = data['project_info']
        client = data['client'][0]
        
        return {
            'apiKey': client['api_key'][0]['current_key'],
            'appId': client['client_info']['mobilesdk_app_id'],
            'messagingSenderId': project_info['project_number'],
            'projectId': project_info['project_id'],
            'storageBucket': project_info['storage_bucket']
        }
    except Exception as e:
        print(f"❌ Error parsing google-services.json: {e}")
        return None

def generate_firebase_options_dart(android_config, web_config):
    """Generate firebase_options.dart file"""
    
    dart_content = f'''// File generated by configure_firebase_auto.py script
// DO NOT EDIT. Make changes to the script and regenerate.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {{
  static FirebaseOptions get currentPlatform {{
    if (kIsWeb) {{
      return web;
    }}
    switch (defaultTargetPlatform) {{
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }}
  }}

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '{web_config["apiKey"]}',
    appId: '{web_config["appId"]}',
    messagingSenderId: '{web_config["messagingSenderId"]}',
    projectId: '{web_config["projectId"]}',
    authDomain: '{web_config["authDomain"]}',
    storageBucket: '{web_config["storageBucket"]}',
    measurementId: '{web_config.get("measurementId", "")}',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '{android_config["apiKey"]}',
    appId: '{android_config["appId"]}',
    messagingSenderId: '{android_config["messagingSenderId"]}',
    projectId: '{android_config["projectId"]}',
    storageBucket: '{android_config["storageBucket"]}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '{android_config["apiKey"]}',
    appId: '{android_config["appId"]}',
    messagingSenderId: '{android_config["messagingSenderId"]}',
    projectId: '{android_config["projectId"]}',
    storageBucket: '{android_config["storageBucket"]}',
    iosBundleId: 'com.travellooply.app',
  );
}}
'''
    return dart_content

def main():
    print("🔧 Configuring Firebase for Travellooply...")
    print()
    
    # Paths
    project_root = '/home/user/flutter_app'
    google_services_path = os.path.join(project_root, 'android/app/google-services.json')
    firebase_options_path = os.path.join(project_root, 'lib/firebase_options.dart')
    config_file_path = os.path.join(project_root, 'lib/config/firebase_config.dart')
    
    # Step 1: Extract Android config
    print("📱 Step 1: Extracting Android configuration from google-services.json...")
    android_config = extract_android_config(google_services_path)
    
    if not android_config:
        print("❌ Failed to extract Android configuration")
        return False
    
    print(f"   ✅ Project ID: {android_config['projectId']}")
    print(f"   ✅ App ID: {android_config['appId']}")
    print()
    
    # Step 2: Generate firebase_options.dart
    print("🌐 Step 2: Generating firebase_options.dart with Web & Android configs...")
    dart_content = generate_firebase_options_dart(android_config, WEB_CONFIG)
    
    with open(firebase_options_path, 'w') as f:
        f.write(dart_content)
    
    print(f"   ✅ Created: lib/firebase_options.dart")
    print()
    
    # Step 3: Update firebase_config.dart to enable real Firebase
    print("🔄 Step 3: Enabling REAL Firebase mode...")
    config_content = '''/// Firebase Configuration
/// 
/// Toggle this to switch between mock and real Firebase implementations.
/// 
/// - **false**: Uses mock services with in-memory data (for demo/testing)
/// - **true**: Uses real Firebase services (requires firebase_options.dart)

class FirebaseConfig {
  /// Set to true to use real Firebase backend
  static const bool USE_REAL_FIREBASE = true;
}
'''
    
    with open(config_file_path, 'w') as f:
        f.write(config_content)
    
    print(f"   ✅ Updated: lib/config/firebase_config.dart")
    print(f"   ✅ USE_REAL_FIREBASE = true")
    print()
    
    # Step 4: Summary
    print("=" * 60)
    print("✅ FIREBASE CONFIGURATION COMPLETE!")
    print("=" * 60)
    print()
    print("📋 What was configured:")
    print("   • Android app configuration (google-services.json)")
    print("   • Web app configuration (firebaseConfig)")
    print("   • Generated lib/firebase_options.dart")
    print("   • Switched app to REAL Firebase mode")
    print()
    print("🚀 Next Steps:")
    print("   1. Initialize Firebase in main.dart:")
    print("      await Firebase.initializeApp(")
    print("        options: DefaultFirebaseOptions.currentPlatform,")
    print("      );")
    print()
    print("   2. Rebuild Flutter app to apply changes")
    print()
    print("⚠️  Important:")
    print("   • Create Firestore database in Firebase Console")
    print("   • Configure Authentication providers (Email/Password)")
    print("   • Set up Firestore security rules")
    print()
    
    return True

if __name__ == '__main__':
    success = main()
    exit(0 if success else 1)
